### ISSUE TITLE
burpui_apiurl not detected

### ISSUE THREAD

**Issue by adocampo** [pablodav/burp_server_reports#10]
I've just discovered burp-reports and I wanted to try.

I've just installed a new burp2 instance, a burp-ui 0.5.0 and latest burp-server-reports.
burp server backs up testclient without problem, burp-ui reflects that.
Burp-UI runs with: burp-ui -- -h 0.0.0.0 -p 8080

On the burp-reports side, I've generated a default config file with
`burp-reports --write_config -c /etc/burp/burp-reports.conf`
And I've added manually under [common] section this:
burpui_apiurl = http://admin:PlainTextPassword@localhost:8080/api/
but when I execute `burp-reports --report print` it complains saying

> burpui_apiurl is required in cmd or in config common section

Putting that URL on a browser, gave me a 404, but http://192.168.101.81:8080/api/doc asks for a password and enter into API documentation.

So, I have doubts regarding if I'm doing something wrong, I need to put the password encoded or it simply wants the default flask port instead a custom port

**Comment by pablodav** [comment]
You are doing it well, but you forgot to use the config when run the report: 

`burp-reports -c /etc/burp/burp-reports.conf --report print`

You can use any config in this way. 

This behaviour is because you can use burp-reports without config (using defaults), or you can also use the config and specify another burp-ui api url at command line using: 

`-ui [BURPUI_APIURL], --burpui_apiurl [BURPUI_APIURL]`

I can recommend also to you my roles to do all automatic: 

https://github.com/grke/burp/wiki/Automated-deploy-and-maintenance

Kind regards,
Pablo.

**Comment by pablodav** [comment]
Hello, 

Have you seen my response? 
It is actually working fine using that syntax.

**Comment by adocampo** [comment]
Sorry Pablo, I have been out of the office this week and until monday I
can't be able to test it. I'll report back ;)




2017-05-19 18:17 GMT+02:00 Pablo Estigarribia <notifications@github.com>:

**Comment by adocampo** [comment]
Hi there, 

Still having problems:
```
 # burp-reports -c /etc/burp/burp-reports.conf --report print
 request failed to get http://192.168.101.81:8080/api/servers/stats
 Traceback (most recent call last):
   File "/usr/local/bin/burp-reports", line 11, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/__main__.py", line 192, in main
     cli_execution(options)
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/__main__.py", line 160, in cli_execution
     clients_dict = bui_api_clients_stats(burpui_apiurl, detail=options.detail)
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/__main__.py", line 79, in bui_api_clients_stats
     bui_clients = BUIClients(burpui_apiurl=burpui_apiurl)
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/interfaces/burpui_api_interface.py", line 18, in __init__
     self.clientsobj = Clients(apiurl=burpui_apiurl)
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/backends/burpui_api.py", line 24, in __init__
     self.IsMultiAgent = self._is_multi_agent()
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/backends/burpui_api.py", line 59, in _is_multi_agent
     burpui_servers = get_url_data(serviceurl)
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/lib/urlget.py", line 113, in get_url_data
     raise e
   File "/usr/local/lib/python3.5/dist-packages/burp_reports/lib/urlget.py", line 99, in get_url_data
    raise ValueError('No data from response')
 ValueError: No data from response
 ```

 Perhaps is because it cannot reach anything?
```
 # wget --user user --password password http://@192.168.101.81:8080/api/
 --2017-05-22 14:54:52--  http://192.168.101.81:8080/api/
 Connecting to 192.168.101.81:8080... connected.
 HTTP request sent, awaiting response... 404 NOT FOUND
 2017-05-22 14:54:52 ERROR 404: NOT FOUND
```

**Comment by pablodav** [comment]
not sure if burpui api is responding correctly to your petition, could be something related to burpui config or nginx/apache in the middle?. 

I use my burpui ansible role for production and Ziirish demo to test this software, maybe is something that your burpui is not responding. I would recommend you to use my ansible role, as it makes everything easier. 

Thanks a lot for reporting this issue! You are the first person here, so I'm very happy to help you. But please also be patient as these kind of issues could need some time to debug. 

Try to connect with curl to you burpui api, you can try directly on localhost and see if it responds: 

This is my test with curl
```shell
curl --user "admin":"password" http://localhost:5000/api/servers/stats
[{"clients": 85, "name": "server1", "alive": true}, {"clients": 142, "name": "server2", "alive": true}, {"clients": 40, "name": "server3", "alive": true}, {"clients": 83, "name": "server3", "alive": true}, {"clients": 23, "name": "Linux", "alive": true}]
```

you can also use `--debug` option on `burp-reports`, but as what I see there is no response from burpui. 

In some other projects, like ansible I had to upgrade `urllib3`, try: 

    sudo pip install -U urllib3 requests

if upgrading `urllib3` helps, please use `pip freeze | grep urllib3` to show me your `urllib3` version, so I will add it to `setup.py` as a minimum required version to avoid this issue to happen again.

**Comment by adocampo** [comment]
Glad to help! :D
Time difference between us will slow even more the fix, but I'm used to it. Anyway, I've just connected via VPN to my workplace and I've tested what you said. I wasn't using ansible at the moment because I'm not confortable enough with it yet, and I've set up several burp (1.X)  and burp-ui instances on several clients manually, so I have enough experience with them. (If you consider it's very easy to set up an ansible environment, please guide me and I can do it). Is the first time I'm playing with burp 2.x but for the backup side, averything seems working just fine.

I have no other web server rather than the embedded flask's on burp-ui, I've tried both port 8080 and defautls 5000, the boths returns nothing:
```
curl --user "admin":"password" http://localhost:5000/api/servers/stats
[]
```
Just like browsing it
http://storage1.static.itmages.com/i/17/0522/h_1495477434_3404196_5396327495.png

--debug option on the burp-reports shows the same output than without it.

As browsing through the api shows nothing at all, I hardly doubt that is your application's fault, it must be something I've missconfigured or something else... Perhaps the ansible way should help...

(PD: y encima tenemos que hablarnos en inglés para que nos entienda la gente xD)

**Comment by pablodav** [comment]
haa pero si hablás español no hay problema :), seguimos en español! (I think there is no one else reading this for now). 

Mi zona horaria es GMT-3 en Uruguay :) 

The output `[]` means your burp-ui is standalone installation (puse esto en inglés para que entiendan esto si es que alguien más lo lee). 

Voy a hacer una prueba con una instalación "standalone", no lo he probado así y creo que no tengo ninguna prueba automática disponible en standalone porque tanto mis servidores como el demo de Ziirish es multi-agent. 

ansible es realmente sencillo de comenzar, tengo pendiente armar un paso a paso para nueva gente que se introduzca en esto pero la intro oficial puede servir (aunque creo que realmente puedo hacer algo mejor de lo que hay hecho para una introducción). Cuándo lo arme te paso el link por este issue. 

Cuándo pueda probar un standalone respondo este issue denuevo.

**Comment by adocampo** [comment]
Yo estoy en GMT+2 (horario de verano) al otro lado del charco ;) No hay problema en escribir en inglés pero si por ahora somos tú y yo, mejor en castellano :3 Tú mandas!
Sí, mi escenario es standalone, con lo que si le echas un vistazo a ver si puedes reproducir tú mismo el error, estupendo.
Quedo a la espera de eso, y si haces un step by step del ansible, lo hago inmediatamente :)

**Comment by pablodav** [comment]
Confirmo que hay un bug para el `standalone` mode. 

Si precisas usar esta funcionalidad con urgencia, tengo seguridad que funciona en `multi-agent` mode. 

Voy a darle prioridad a solucionar este bug y lanzar el release 1.2.4, así como agregaré un test automático para standalone mode usando los roles de ansible que use mismo para levantar esto. 

```python
 burp-reports -ui http://admin:admin@172.17.0.2:8080/
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2
request failed to get http://172.17.0.2:8080/servers/stats
Traceback (most recent call last):
  File "/usr/local/bin/burp-reports", line 11, in <module>
    load_entry_point('burp-reports', 'console_scripts', 'burp-reports')()
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/__main__.py", line 192, in main
    cli_execution(options)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/__main__.py", line 160, in cli_execution
    clients_dict = bui_api_clients_stats(burpui_apiurl, detail=options.detail)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/__main__.py", line 79, in bui_api_clients_stats
    bui_clients = BUIClients(burpui_apiurl=burpui_apiurl)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/interfaces/burpui_api_interface.py", line 18, in __init__
    self.clientsobj = Clients(apiurl=burpui_apiurl)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/backends/burpui_api.py", line 24, in __init__
    self.IsMultiAgent = self._is_multi_agent()
  File "/usr/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/backends/burpui_api.py", line 59, in _is_multi_agent
    burpui_servers = get_url_data(serviceurl)
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/lib/urlget.py", line 113, in get_url_data
    raise e
  File "/home/v744989/gitprojects/burp_server_reports/burp_reports/lib/urlget.py", line 64, in get_url_data
    req.json()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
El problema se da porque en la línea: 64: de urlget.py https://github.com/pablodav/burp_server_reports/blob/master/burp_reports/lib/urlget.py#L64

estoy tratando de transformar en json lo que recibo de burpui, pero debería verificar si es posible antes, en este caso verificar si está vacío. 

voy a revisar si es que no debería agregar un paso distinto y no usar nada de urlget.py para verificar si es `standalone`, tal vez sea más sencillo así.

**Comment by pablodav** [comment]
En el anterior test había olvidado el /api/ al final, pero de todas formas implementé un fix para hacer más robusto el chequeo de casos donde quiero saber si es multi-agent o `standalone`.

```shell
burp-reports -ui "http://admin:admin@172.17.0.2:8080/api/"

 burp report                                                                                      2017-05-23 14:04:57
                           Name     Date(local)  Time(local)  State        Phase
                           monitor   ---          ---         idle          ---
                       test_client  2017-05-23   13:37:56     idle          ---
```

este fix funcionó como se ve arriba, voy a correr algunos tests más para confirmar que no exista otro error antes de subir el nuevo release.

**Comment by pablodav** [comment]
pasó todos los tests y ahora hay un nuevo release en pip

`sudo pip3 install burp_reports==1.2.4`

o 

`pip3 --user install burp_reports==1.2.4`

**Comment by pablodav** [comment]
Espero esto haya funcionado y hayas logrado usar todas las funciones que provee burp-reports. 

Espero poder ayudar en cualquier otro problema o si tienes alguna solicitud nueva será un placer ayudarle!

**Comment by adocampo** [comment]
Sí, funcionó! :) 
Bueno, estoy jugueteando con burp-reports, ya te iré diciendo si veo alguna cosilla :)
Muchas gracias!
