### ISSUE TITLE
urllib3.exceptions.LocationParseError: Failed to parse: http://xxx:xxx@localhost:5000/api/servers/stats

### ISSUE THREAD

**Issue by ngatti-asso** [pablodav/burp_server_reports#25]
Hi Pablo.  I don't know if you are still mantaining this project.
I am struggling to get reports working. I have installed all packages via ansible and burpui is working and I am using it on a daily basis.
But I can't get burp-reports working. This is the error I am getting:

```
# burp-reports --report -ui http://xx:xx@localhost:5000/api/
Traceback (most recent call last):
  File "/usr/local/bin/burp-reports", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/__main__.py", line 193, in main
    cli_execution(options)
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/__main__.py", line 161, in cli_execution
    clients_dict = bui_api_clients_stats(burpui_apiurl, detail=options.detail)
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/__main__.py", line 80, in bui_api_clients_stats
    bui_clients = BUIClients(burpui_apiurl=burpui_apiurl)
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/interfaces/burpui_api_interface.py", line 18, in __init__
    self.clientsobj = Clients(apiurl=burpui_apiurl)
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/backends/burpui_api.py", line 30, in __init__
    self.IsMultiAgent = self._is_multi_agent()
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/backends/burpui_api.py", line 67, in _is_multi_agent
    burpui_servers = get_url_data(serviceurl, check_multi=True)
  File "/usr/local/lib/python3.8/dist-packages/burp_reports/lib/urlget.py", line 44, in get_url_data
    purl = parse_url(serviceurl)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://xx:xx@localhost:5000/api/servers/stats

```
and If I run a CURL on that URL, this is what I can see:

```
# curl http://xx:xx@localhost:5000/api/servers/stats
[]

```

seems that authentication works ok, but I don't know what the api is supposed to reply there.

Thanks.

**Comment by pablodav** [comment]
Thanks for reporting!

I still maintain it but in more "reactive" way than in the past, as I don't have too much time, but if someone like you contact me I will try to solve any issue or reply as fast as possible so the community will feel supported 👍

https://github.com/pablodav/burp_server_reports/blob/master/burp_reports/backends/burpui_api.py#L67

This part of the code only checks if server is multi-agent or standalone.

As comments in the code says:

```python
# Comments from Ziirish:
        # You'd better test /api/servers/stats
        # It returns an empty list ([]) when there are no agents and then switch back to
        # the "standalone" mode.
        # Now if the list is not empty, you'll have something like:
        # [
        # {
        #   'alive': true,
        #   'clients': 2,
        #   'name': 'burp1',
        # },
        #  {
        #   'alive': false,
        #   'clients': 0,
        #   'name': 'burp2',
        #   },
        #  ]
```
Last time I have updated tox tests in develop branch I was not able to test 100% python3.7 and python3.8,:
https://travis-ci.org/github/pablodav/burp_server_reports/branches

But you can try this in python3 console, I have tried this in my python3.8 at fedora and it works fine so maybe something in your environment to find?:

```python
>>> import urllib3
>>> from urllib3.util import parse_url
>>> service_url = 'http://xx:xx@localhost:5000/api/servers/stats'
>>> purl = parse_url(service_url)
```
you can also show version of urllib:

```shell
python -m pip show urllib3
Name: urllib3
Version: 1.25.7
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: c:\users\k415228\appdata\roaming\python\python35\site-packages
Requires:
Required-by: selenium, requests
```

**Comment by pablodav** [comment]
Also check if your password has any special character, not sure but you can try.

**Comment by ngatti-asso** [comment]
First of all, thanks yuou Pablo for taking the time and answer me.
The password had some special characters that I replaced, but it is still failing. 

I am using python 3.8 on an Ubuntu 20.04 server.
This is my urllib version:
```

python3 -m pip show urllib3
Name: urllib3
Version: 1.25.8
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/lib/python3/dist-packages
Requires:
Required-by: burp-reports

```

I will dig a bit in the code. If I am able to find the issue I'll let you know.

**Comment by ngatti-asso** [comment]
And this is the result of the test:

```
>>> import urllib3
>>> from urllib3.util import parse_url
>>> service_url = 'http://xx:xx@localhost:5000/api/servers/stats'
>>> purl = parse_url(service_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://xx:xx@localhost:5000/api/servers/stats

```

Seems to be an issue with urllib3.

Also, a simple localhost query also fails:

```
>>> import urllib3
>>> from urllib3.util import parse_url
>>> service_url = 'http://localhost'
>>> purl = parse_url(service_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://localhost

```
And there is a running webserver on port 80 that I can reach via curl/wget from command line. I'm lost.

**Comment by pablodav** [comment]
very strange case, could be some buggy urllib3 installed from the rpm or deb packages?

First upgrade pip to latest version.

    sudo python3 -m pip install -U pip

Did you try to upgrade it with pip?

    sudo python3 -m pip install -U urllib3

You can also try to install only in user profile and try the version on user profile

    python3 -m pip install --user -U urllib3
    python3
    test it here....

**Comment by ngatti-asso** [comment]
I updated urllib3 and it started to work!
I had 1.25.8 and once I update it to 1.25.10 the errors disappeared. 
Thanks again Pablo for pointing in the right direction.
